[package]
name = "fitsort-rs"
version = "0.1.0"
edition = "2024"
readme = "README.md"
description = "A rust rewrite of fitsort, used to read dfits output"
authors = ["Trystan Lambert <trystan.lambert@uwa.edu.au>"]
license = "MIT"
repository = "https://github.com/TrystanScottLambert/fitsort-rs"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }


[[bin]]
path = "src/main.rs"
name = "fitsort"

[profile.release]
opt-level = 3
debug = "none"
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = "abort"
incremental = false
codegen-units = 1
